[options]
; Dirección del servidor de base de datos
db_host = db
db_port = 5432
db_user = odoo
db_password = db_luis

; Configuración de addons
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons

; Modo de ejecución
; workers = 4

; Logging
logfile = /var/log/odoo/odoo.log
log_level = info

; Interfaz
xmlrpc_port = 8069

; Idioma y localización
language = es_ES
